POST http://localhost:4100/users
Content-Type: application/json

{
  "name": "jackson1",
  "phone_no": "18-00-80",
  "email": "jackson1@gmail.com",
   "role": "expert",
  "image": "https://images.pexels.com/photos/1615776/pexels-photo-1615776.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1", 
  "password": "expert"
}


### get all user

GET http://localhost:4100/users
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNlY2JlM2NiLTFhMDMtNGJlOC04ZWRjLTdjMzI4YmZmMTFkNyIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzEwNzU0MDAxLCJleHAiOjE3MTEwMTMyMDF9.O9BWeBgfq1-8NQPf7SaWyOcfYlCTvO5r6hdzpG2FJeQ


### get 1 user by id

GET http://localhost:4100/users/7d1112c0-8e0a-4dc7-808c-85e932e7f782
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNlY2JlM2NiLTFhMDMtNGJlOC04ZWRjLTdjMzI4YmZmMTFkNyIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzEwNzU0MDAxLCJleHAiOjE3MTEwMTMyMDF9.O9BWeBgfq1-8NQPf7SaWyOcfYlCTvO5r6hdzpG2FJeQ


### update user

PUT http://localhost:4100/users/update/7d1112c0-8e0a-4dc7-808c-85e932e7f782
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNlY2JlM2NiLTFhMDMtNGJlOC04ZWRjLTdjMzI4YmZmMTFkNyIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzEwNzU0MDAxLCJleHAiOjE3MTEwMTMyMDF9.O9BWeBgfq1-8NQPf7SaWyOcfYlCTvO5r6hdzpG2FJeQ


{
 "name": "admin",
  "phone_no": "180-000-800",
  "email": "admin@gmail.com",
   "role": "",
  "image": "https://images.pexels.com/photos/1615776/pexels-photo-1615776.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
  
}

### delete a user
DELETE http://localhost:4100/users/delete/83414a60-e1e3-4bbc-82df-1342bb90ba45
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTExMmMwLThlMGEtNGRjNy04MDhjLTg1ZTkzMmU3Zjc4MiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6Imh0dHBzOi8vZXhhbXBsZS5jb20vcHJvZmlsZS1pbWFnZS5qcGciLCJpYXQiOjE3MTA3ODU1MTIsImV4cCI6MTcxMTA0NDcxMn0.KNORNBDQyOszCu-DyHx9kprQtw4DHHrg7h52gGnAXT0