POST http://localhost:4100/auth/login
Content-Type: application/json

{
  "email": "godwin@gmail.com",
  "password": "user"
}


###
GET http://localhost:4100/auth/checkdetails
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM3OTM1ODQyLThlZWMtNDg0Zi04ZmViLTdhYzQ5NjgyNjhiMSIsImVtYWlsIjoiamFjazIyQGdtYWlsLmNvbSIsInJvbGUiOiJleHBlcnQiLCJpYXQiOjE3MTE0NjA5ODQsImV4cCI6MTcxMTcyMDE4NH0.LMErzJJdM5rVD_WRLfB1r_QMLJKJ2ukkdIIrVWwvuzs